### ISSUE TITLE
Particle errors

### ISSUE THREAD

**Issue by tenplus1** [minetest-mods/nether#81] opened 2024-11-20 13:43 UTC
When in nether and seeing fumerole particles or breaking magma block, the particles show this error in latest 5.11dev:

ERROR[Main]: generateImage(): baseimg is NULL (attempted to create texture "")
ERROR[Main]: generateImagePart(): baseime == NUL for part_of_name="[colorize:#FB0:255", cancelling.
ERROR[Main]: generateImage(): Failed to generate "[colorize:#FB09:255"
ERROR[Main]: part of texture "^[colorize:#FB0:255"
ERROR[Main]: generateImage(): baseimg is NULL (attempted to create texture "^[colorize:#FB0:255")

**Comment by Treer** [comment] 2024-12-07 06:37
Looks like the regression happened between [5.8](https://github.com/minetest/minetest/commit/49ce5a2de633d751080a0c97b802ae48190bf911) and [5.9](https://github.com/minetest/minetest/commit/835dd01fa163df815215b8c694af0910657602b6)

**Comment by SmallJoker** [comment] 2024-12-25 17:55
Fixed by #82.

**Closed by SmallJoker** 2024-12-25 17:55 UTC
