### ISSUE TITLE
generateImage(): baseimg is NULL

### ISSUE THREAD

**Issue by KINGamerx7KerrS** [minetest-mods/nether#84] opened 2024-12-24 22:54 UTC
![Screenshot (77)](https://github.com/user-attachments/assets/008c376f-dad5-4a6f-a671-9d17aba37514)

Not sure what causes this error, but it happens with Luanti 5.10, and last version of Minetest game. No other mods installed besides Nether. The errors don't break anything.

**Comment by SmallJoker** [comment] 2024-12-25 17:55
Duplicate of #81? Please retest with latest master.

**Closed** 2024-12-31 09:50 UTC
